# плейсхолдеры которые поддерживает плагин для PlaceholderAPI
#-------------------------------------------------------------
# %prize_balance% - баланс розыгрыша
# %prize_time_left% - оставшееся время до начала розыгрыша
# %ticket_amount% - количество билетов игрока


# команды плагина
#-------------------------------------------------------------
# /prizeevent - prizeevent.player.command
# /prizeeventAdmin - prizeevent.admin.command



# настройка анимации bossBar
boss-bar-info:
  default-text: "Скоро начнется розыгрыш! Набранная сумма %prize_balance%"
  default-color: BLUE
  default-style: SOLID

  # анимация после достижения определенного промежутка времени
  after:
    time: "30s"
    text: "Набранная сумма %prize_balance%. Ивент начнется через %prize_time_left%"
    color: BLUE
    style: SOLID
    # убавление шкалы если true
    # иначе увеличение
    reversed: true
# список времен розыгрыша
event-times:
  - "1m"
  - "2m"

# формат времени для плейсхолдера time_left
# всего 6 '%s' и в зависимости от кол-во секунд будет выводиться разная информация
# время идет по порядку от месяца до секунд
placeholder-time-format: "%s часов, %s минут, %s секунд"

# логировать отсутствие текста в конфиге
log-messages: true
messages:
  no-one-payed:
    - "ни кто не купил билеты розыгрыш обновляется"
  not-online:
    - "игрок не в сети"
  invalid-amount:
    - "неверное количество билетов"
  ticket-given:
    - "билеты выданы игроку"
  ticket-taken:
    - "билеты сняты у игрока"
  config-reloaded:
    - "конфиг перезагружен"
  invalid-arguments:
    - "неверные аргументы"
  admin-help:
    - "/prizeeventAdmin give <игрок> <количество билетов> - выдать билеты игроку"
    - "/prizeeventAdmin take <игрок> <количество билетов> - снять билеты у игрока"
    - "/prizeeventAdmin reload - перезагрузить конфиг"
    - "/prizeeventAdmin info <игрок> - информация о билетах игрока"
    - "/prizeeventAdmin help - помощь по камандам администратора"
  player-help:
    - "/prizeevent info - информация о купленных билетах"
    - "/prizeevent help - помощь по командам игрока"
  player-info-for-admin:
    - "игрок: %player_name%"
    - "количество билетов: %prize_tickets_amount%"
  player-info:
    - "количество билетов: %prize_tickets_amount%"
  event-skipped:
    - "процесс ожидания пропущен."
  event-started:
    - "розыгрыш начался!"

# максимальный достигнутый баланс розыгрыша
max-prize-balance: -1
# сколько дают за вход нового игрока в сервер
balance-give: 200


# настройка gui анимации
# выигранный слот находится на 6 слоте
prize-roulette-gui:
  title: "Выйгрыш приза"
  size: 27
  sound: "random.anvil_use"
  win-sound: "AMBIENT_BASALT_DELTAS_LOOP"
  time-animation: 5
  animation-slots: [ 13 ]


decorate:
  # все настройки предмета
  # example-id
  #   material: DIRT
  #   display-name: " "
  #   lore: [ " " ]
  #   slots:
  #     - 0
  #   flags: [ HIDE_ENCHANTS ]
  #   model-data: 0
  #   enchantments:
  #     DURABILITY: 1



